### ISSUE TITLE
Y axis outside window.

### ISSUE THREAD

**Issue by ghayne** [mblackstock/node-red-contrib-data-view#3] opened 2020-12-27 11:50 UTC
On Opera running on Linux I get:
![image](https://user-images.githubusercontent.com/29737866/103170112-ae53df00-4839-11eb-8969-2526ab6a6af3.png)

[EDIT - The same on Chrome]

**Comment by mblackstock** [comment] 2020-12-27 17:48
Thanks, yes, I probably need to adjust the margins a bit, maybe dynamically

**Comment by mblackstock** [comment] 2020-12-30 22:57
fixed on develop

**Comment by ghayne** [comment] 2021-01-02 17:57
Still happening occasionally 0.0.2:
![image](https://user-images.githubusercontent.com/29737866/103463389-e5d3f700-4d23-11eb-942a-d6eebee76677.png)

**Comment by mblackstock** [comment] 2021-01-02 19:53
thanks.  will have another look!

**Comment by mblackstock** [comment] 2021-01-02 23:52
I'm having trouble reproducing the problem with the latest rev.  Any pointers on how to reproduce it would be appreciated.

**Comment by Paul-Reed** [comment] 2021-01-03 00:12
I also can't reproduce here with current rev, it appears correctly formatted for me now.
...maybe browser caching issue??

**Comment by ghayne** [comment] 2021-01-03 10:21
Looks like it was the cache as Paul suggested. Apologies for wasting your time!

**Comment by mblackstock** [comment] 2021-01-03 20:55
👍   no worries! thanks for letting me know.

**Closed as completed by mblackstock** 2021-01-03 20:55 UTC
